version: "3.1"
services:
  mongo:
    image: mongo:latest
    container_name: "zoo-app-container"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: zoo
    volumes:
      - ./init-files/zoodb.js:/docker-entrypoint-initdb.d/zoodb.js:ro

